### PR TITLE
[web] New landing page bg, fixed signup UI

### LINKED ISSUE #33: [web] Use new background animation on the landing page
Currently, our ball animation is quite taxing, especially on mobile devices. Moreover, @sqphoenix wants to use an animating globe background, specifically [this one](https://www.vantajs.com/?effect=globe#(backgroundAlpha:1,backgroundColor:2299196,color:16727937,color2:16777215,maxDistance:20,points:10,showDots:!t,size:0.6000000000000001,spacing:15)).

The task is to replace the old animation with the new one.

### PR DESCRIPTION
**Pull request by JonathanXu1**
Ticket | Title
---|---
closes #33 | [web] Use new background animation on the landing page
#17 | Website does not load for certain devices #17

## Description

- Updated the bg animation as per #33.
- Fixed the extra spacing error on the landing page, by using a div instead of a bootstrap container.
- Properly centered the signup and login cards.

## Screenshots
image
dark version:
image

### CODE REVIEW

File: src/client/components/landing/LandingBody.jsx [hunk 1]
```diff
@@ -8,7 +8,9 @@ import { Canvas } from 'react-three-fiber';
 
 import { Row, Col, Container, Accordion, Card } from 'react-bootstrap';
 
-import Scene from './Scene.jsx';
+//import Scene from './Scene.jsx';
```
Comment (hanburger97) [inline src/client/components/landing/LandingBody.jsx]: You can delete this line :D

File: src/client/components/landing/LandingBody.jsx [hunk 2]
```diff
@@ -28,84 +31,99 @@ class LandingBody extends Component {
...
-              <br />
-              <WhiteLink to={ROUTES.SIGN_UP}><PrimaryButton pill >Get Started</PrimaryButton></WhiteLink>
-              <BlueLink to={ROUTES.DASHBOARD}><SecondaryButton pill outline>Log In</SecondaryButton></BlueLink>
-            </div>
-          </Col>
-          <Col md={6}>
 
+      <div>
+        <div ref={this.vantaRef} className="vh-100">
+          <Row className={Style.Header} className="loremIpsum"> {/* ClassName needed to help init globe animation */}
```
Comment (hanburger97) [inline src/client/components/landing/LandingBody.jsx]: nit: can you give it a more representative name for `className`

File: src/client/components/landing/_base.js [hunk 3]
```diff
@@ -0,0 +1,325 @@
...
+//   }
+// }
+// if (DEBUGMODE) {
+//   extend(ORBITCONTROLS, {
+//     enableZoom: true,
+//     zoomSpeed: 4,
+//     minDistance: 100,
+//     maxDistance: 4500
+//   })
+// }
```
Comment (hanburger97) [inline src/client/components/landing/_base.js]: What do these do? can they be deleted?

File: src/client/components/landing/_base.js [hunk 4]
```diff
@@ -0,0 +1,325 @@
+import {extend, mobileCheck, q, color2Hex} from './helpers.js'
```
Comment (hanburger97) [inline src/client/components/landing/_base.js]: what does this file do? if its Vanta's code, instead we can just use the minified code `vanta.globe.min.js` file from Vanta GH and put it under `...client/vendor/...` so that we dont have to import the entire source code for vanta?

File: src/client/components/landing/vanta.globe.js [hunk 5]
```diff
@@ -0,0 +1,382 @@
+import VantaBase, {VANTA} from './_base.js'
```
Comment (hanburger97) [inline src/client/components/landing/vanta.globe.js]: Same comment as the one above for _base

File: src/client/styles/pages/Login.less [hunk 6]
```diff
@@ -1,17 +1,16 @@
...
-  background-size: 400px auto, 400px auto;   
-  height: 100vh;
-  width: auto;
-  z-index: -1;
+  // background-position: bottom left, top right;
+  // background-repeat: no-repeat, no-repeat;
+  // background-size: 400px auto, 400px auto;   
+  // height: 100vh;
+  // width: auto;
+  // z-index: -1;
```
Comment (hanburger97) [inline src/client/styles/pages/Login.less]: We can delete these if they are no longer used

**Comment by hanburger97** [comment]
Also how does it work for the Light/Dark version? will Users be able to toggle or is it hard coded for now?

File: src/client/components/landing/LandingBody.jsx (hunk 1 above)
Comment (JonathanXu1) [reply src/client/components/landing/LandingBody.jsx]: Ok, will do!

File: src/client/components/landing/_base.js (hunk 3 above)
Comment (JonathanXu1) [reply src/client/components/landing/_base.js]: I think that's for the other animations offered by the library? _base.js was a dependancy that I needed to download from the repo to get the animation working.

File: src/client/components/landing/_base.js (hunk 4 above)
Comment (JonathanXu1) [reply src/client/components/landing/_base.js]: > Also how does it work for the Light/Dark version? will Users be able to toggle or is it hard coded for now?

It should be hard-coded. I was working with @sqphoenix on the color design of the animation, and I posted screenshots of different color combos to help with that.

**Comment by JonathanXu1** [comment]
> Also how does it work for the Light/Dark version? will Users be able to toggle or is it hard coded for now?

It should be hard-coded. I was working with @sqphoenix on the color design of the animation, and I posted screenshots of different color combos to help with that.

File: src/client/components/landing/_base.js (hunk 3 above)
Comment (JonathanXu1) [reply src/client/components/landing/_base.js]: > There's only one issue really, Im not sure why we are including the entire source code for Vanta (_base.js and vanta.globe.js) is there a particular reason why we arent using the `vanta.globe.min.js` instead? thinking 

My bad, I didn't realize they had a min file for vanta globe! I'll commit something that uses that instead.
